title: 'https://t.me/videorussia55'
description: >-
  http://siski.tv/vid/%D1%80%D0%B0%D0%BA%D0%BE%D0%BC+%D1%81%D0%B8%D1%81%D1%8F%D1%81%D1%82%D1%83%D1%8E+%D0%BD%D0%B0+%D1%83%D0%BB%D0%B8%D1%86%D0%B5
template:
  repo: 'https:t.mevideorussia55-template'
  name: 'https:t.mevideorussia55'
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
